### ISSUE TITLE
download FFHQ tfrecord dataset related issue

### ISSUE THREAD

**Issue by howtowhy** [apple/ml-gmpi#21]
Hello, thank you for good research.
I want to train your model and refer your research.
But, when I download and preprocessing FFHQ, there is some problem.
FFHQ tfrecord -> FFHQ 256 preprocessing is suggested.
But the FFHQ tfrecord google drive api is disconnected everytime. (how do you download it?)
Is there any other option I can download it ? 
There is no repository who provide 13G FFHQ 256 dataset...
If you give me a favor, It will be a great help. Thank you.

**Comment by Xiaoming-Zhao** [comment]
Thanks a lot for your interest in this work.

>But the FFHQ tfrecord google drive api is disconnected everytime. (how do you download it?)

I actually just downloaded it via the browser. I know it is a kinda headache. But due to the legal and privacy issue, we are unable to release the processed data (see https://github.com/apple/ml-gmpi/issues/2#issuecomment-1197387492).

>If you give me a favor, It will be a great help. Thank you.

Even though you may need to download the data yourself, here are two things that might be helpful:
1. Instead of downloading the tfrecords version of 200GB, you can download the smaller one of only 90GB. They have been verified to be the same (see https://github.com/apple/ml-gmpi/issues/2#issuecomment-1196353849 and https://github.com/apple/ml-gmpi/issues/2#issuecomment-1199021388).
2. People said before that you could clone the data to your own repo first and then use API to download it (see https://github.com/apple/ml-gmpi/issues/2#issuecomment-1193467194).

Hope these help.
